export default {
  "0110": "Alguém te quer, mas espera por uma atitude sua.",
  "0220": "Notícias boas estão a caminho.",
  "0330": "Alguém te deseja. Fique atento(a) para descobrir quem é.",
  "0440": "Se traiu alguém, deve pensar melhor sobre seus próprios atos.",
  "0550": "Receberá uma boa surpresa em breve.",
  "1001": "A pessoa que você ama já está apaixonada por outra. É melhor não criar esperanças.",
  "1221": "Alguém próximo pode estar falando mal de você. Fique atento(a) às pessoas ao seu redor.",
  "1331": "Fique atento(a) a uma possível reviravolta em casa ou no trabalho e tente lidar com isso da melhor forma possível.",
  "1441": "Você pode ter perdido algo ou alguém de grande valor.",
  "1551": "Alguém está caidinho(a) por você (e pode ser uma pessoa do seu passado!).",
  "2002": "Uma pessoa sente saudade de você.",
  "2112": "Uma pessoa deseja muito o seu bem. Seja grato(a).",
  "2332": "Preste atenção a quem você chama de 'amigo(a)' e não revele detalhes de sua vida a qualquer um.",
  "0101": "Novidades na vida amorosa.",
  "0202": "Você sabe do que é capaz.",
  "0303": "Pense mais em você.",
  "0404": "Aprenda a lidar com os altos e baixos.",
  "0505": "Seu esforço dará frutos.",
  "0606": "Um desafio se aproxima.",
  "0707": "Evite falar sobre o seu sucesso.",
  "0808": "Evite mal-entendidos.",
  "0909": "Use sua intuição a seu favor.",
  "1010": "Sinal de mudanças positivas.",
  "1111": "Você é o porto-seguro de alguém.",
  "1212": "Momento bom no amor ou trabalho.",
  "1313": "Seu desejo será atendido.",
  "1414": "Confie em você!",
  "1515": "Aquela pessoa te ama.",
  "1616": "Momento para refletir.",
  "1717": "Pausa para conhecer a si mesmo.",
  "1818": "Não deixe abusarem da sua bondade.",
  "1919": "Relacionamento amoroso à vista.",
  "2020": "Náo minta para você.",
  "2121": "Todos podem contar com você.",
  "2222": "Você realizará grandes feitos.",
  "2323": "Atenção àqueles que se impõem à sua vontade.",
  "0000": "Realize uma mudança interna."
}